# Generated by Django 3.2.12 on 2022-03-12 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=60, unique=True)),
                ('description', models.CharField(db_column='descripcion', max_length=60, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_marca',
            },
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_capacidad',
            },
        ),
        migrations.CreateModel(
            name='EModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=20, unique=True)),
                ('description', models.CharField(db_column='Descripcion', max_length=100, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_modelo',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
                ('employee_id', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_equipo',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_tipo_equipo',
            },
        ),
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_archivo_sistema',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_frecuencia',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_generacion',
            },
        ),
        migrations.CreateModel(
            name='HardwareEquipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.TextField(db_column='serie', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('quantity', models.IntegerField(db_column='cantidad')),
                ('observation', models.TextField(db_column='observacion')),
                ('equipment_id', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment')),
            ],
            options={
                'db_table': 'inv_equipo_detalle_hardware',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_inventario',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_tipo_item',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='nombre', max_length=255)),
                ('published_by', models.TextField(db_column='publicado_por', max_length=255)),
                ('install_date', models.DateField(db_column='fecha_instalacion')),
                ('version', models.TextField(db_column='version', max_length=100)),
                ('link_support', models.TextField(db_column='link_soporte', max_length=500)),
                ('link_help', models.TextField(db_column='link_ayuda', max_length=500)),
                ('link_update', models.TextField(db_column='link_actualizacion', max_length=500)),
                ('comment', models.TextField(db_column='comentario', max_length=1000)),
            ],
            options={
                'db_table': 'inv_software',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_tipo_transaccion',
            },
        ),
        migrations.CreateModel(
            name='TransactionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('type_trx', models.ForeignKey(db_column='id_tipo_trx', on_delete=django.db.models.deletion.CASCADE, to='inventory.transactiontype')),
            ],
            options={
                'db_table': 'inv_motivo_transaccion',
            },
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='nombre', max_length=255)),
                ('capacity', models.DecimalField(db_column='capacidad', decimal_places=2, max_digits=5)),
                ('free_space', models.DecimalField(db_column='espacio_libre', decimal_places=2, max_digits=5)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('eq_detail_id', models.ForeignKey(db_column='id_equipo_detalle_hardware', on_delete=django.db.models.deletion.CASCADE, to='inventory.hardwareequipmentdetail')),
                ('file_sys', models.ForeignKey(db_column='id_file_system', on_delete=django.db.models.deletion.CASCADE, to='inventory.filesystem')),
            ],
            options={
                'db_table': 'inv_particion',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description', max_length=255, verbose_name=inventory.models.ItemType)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('quantity', models.IntegerField(db_column='cantidad')),
                ('value', models.IntegerField(db_column='valor')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
                ('capacity_id', models.ForeignKey(db_column='id_capacidad', on_delete=django.db.models.deletion.CASCADE, to='inventory.capacity')),
                ('employee_id', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
                ('eq_type', models.ForeignKey(db_column='id_tipo_equipo', on_delete=django.db.models.deletion.CASCADE, to='inventory.emodel')),
                ('frequency_id', models.ForeignKey(db_column='id_frecuencia', on_delete=django.db.models.deletion.CASCADE, to='inventory.frequency')),
                ('generation_id', models.ForeignKey(db_column='id_generacion', on_delete=django.db.models.deletion.CASCADE, to='inventory.generation')),
                ('location_id', models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
            options={
                'db_table': 'inv_item',
            },
        ),
        migrations.AddField(
            model_name='hardwareequipmentdetail',
            name='inventory_id',
            field=models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='hardwareequipmentdetail',
            name='item_id',
            field=models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.CreateModel(
            name='EquipmentTrx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
                ('employee_id', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eq_type', models.ForeignKey(db_column='id_tipo_equipo', on_delete=django.db.models.deletion.CASCADE, to='inventory.equipmenttype')),
            ],
            options={
                'db_table': 'inv_transaccion_equipo',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_type',
            field=models.ForeignKey(db_column='id_tipo_equipo', on_delete=django.db.models.deletion.CASCADE, to='inventory.equipmenttype'),
        ),
    ]
